version: 2.1
general:
  branches:
    only:
      - source
jobs:
  build:
    docker:
      - image: circleci/python:3.7.10
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: make github

workflows:
  version: 2.1
  deploy_site:
    jobs:
      - build
