version: 2.1
general:
  branches:
    only:
      - source
jobs:
  build:
    docker:
      - image: circleci/python:3.7.10
    steps:
      - add_ssh_keys:
          fingerprints:
            d7:91:35:9c:54:66:53:89:94:ab:69:2a:ef:32:5a:a6
      - checkout
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: make github

workflows:
  version: 2.1
  deploy_site:
    jobs:
      - build
